### ISSUE TITLE
Keepalive should only reset on pingreq

### ISSUE THREAD

**Issue by RangerMauve** [256dpi/mqtt-stack#1]
At the moment it seems that any action from the client is enough to reset the timer, but AFAIK it's supposed to be reset only on pingreq.

**Comment by 256dpi** [comment]
Thanks for the look through. Here's the related section from the spec:

> The Keep Alive is a time interval measured in seconds. Expressed as a 16-bit word, it is the maximum time interval that is permitted to elapse between the point at which the Client finishes transmitting one Control Packet and the point it starts sending the next. It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet [MQTT-3.1.2-23].

**Comment by RangerMauve** [comment]
Thanks for the clarification, I must have misread somewhere. :P
